### ISSUE TITLE
Add an image of a library to home page

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#1]
@Rosarangi 
Add this picture for home page of system (as per requirement of client).
![home1](https://user-images.githubusercontent.com/75560658/101665695-52383f00-3a73-11eb-9393-e461842143a8.jpg)

**Comment by Rosarangi** [comment]
Sandali, I put this image to home page.
![home](https://user-images.githubusercontent.com/74761716/101679022-ca5b3080-3a84-11eb-8348-2b65e987dda4.PNG)
