### ISSUE TITLE
Testing error on Update of user login interface

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#2]
@Rosarangi @JSPrasannicca 
When testing update of user login interface, it was carried two links for **HOME**  page. [http://localhost/lms-main/user/stdLogin.php](url)
![error](https://user-images.githubusercontent.com/75560658/101718850-14b1d100-3ac8-11eb-870d-fa30e0a10e82.PNG)
Please pay attention for this and Let's try to fix this.

**Comment by JSPrasannicca** [comment]
Good Morning Sandali,

We have to fix this.

Sure We'll fix this together.

Thank you for informing.

Best Regards,
J.S.Prasannicca,
Undergraduate,
Sri Lanka Technological Campus,
Ingiriya Road,
Padukka.
0763667041

**Comment by Rosarangi** [comment]
Sandali, I solved that issue. Thanks for pointed out it.
![Screenshot (354)](https://user-images.githubusercontent.com/74761716/101729442-28683200-3ade-11eb-9231-b6aae69156ee.png)
