### ISSUE TITLE
Testing error on "update and delete book" interface

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#3]
@Rosarangi @JSPrasannicca 
When testing **update and delete book** interface, **Library management system** logo is closed by navigation bar.
Please pay attention to fix this error.
![IMG-20201211-WA0011](https://user-images.githubusercontent.com/75560658/101866674-74c77680-3b9f-11eb-8c2e-9fa9c119175c.jpg)

**Comment by JSPrasannicca** [comment]
I have noticed it Sandali.

Let's find a way to fix it.

Thank you for letting me know.

Best Regards,
J.S.Prasannicca,
Undergraduate,
Sri Lanka Technological Campus,
Ingiriya Road,
Padukka.
0763667041

**Comment by Rosarangi** [comment]
I fixed tha issue. thank you for point out it
![Screenshot (373)](https://user-images.githubusercontent.com/74761716/101873486-0093cf80-3bad-11eb-9d57-d965b2516d3d.png)

**Comment by JSPrasannicca** [comment]
Good Work Rosarangi.
Keep it up.

Best Regards,
J.S.Prasannicca,
Undergraduate,
Sri Lanka Technological Campus,
Ingiriya Road,
Padukka.
0763667041
