### ISSUE TITLE
Testing error of "side bar"

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#4]
@Rosarangi @JSPrasannicca 
When testing side bar, **Library management system** logo is closed by side bar. 
Please pay attention to close this error.
![IMG-20201211-WA0011](https://user-images.githubusercontent.com/75560658/101867391-07b4e080-3ba1-11eb-834c-29044bda4bd5.jpg)

**Comment by Rosarangi** [comment]
I fixed that issue. thank you for point out it.
![Screenshot (376)](https://user-images.githubusercontent.com/74761716/101876116-e9a3ac00-3bb1-11eb-980d-31b1f93d662f.png)

**Comment by JSPrasannicca** [comment]
Good job Rosarangi.


Best Regards,
J.S.Prasannicca,
Undergraduate,
Sri Lanka Technological Campus,
Ingiriya Road,
Padukka.
0763667041
