### ISSUE TITLE
Testing error on book category table

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#5]
@Rosarangi @JSPrasannicca 
When testing **book category table** , unfortunately it wasn't shown as we excepted. No book wasn't appeared.
Please pay your attention to fix this error. 
![IMG-20201211-WA0025](https://user-images.githubusercontent.com/75560658/101922795-9010a100-3bf4-11eb-9c55-d641b040246d.jpg)

**Comment by JSPrasannicca** [comment]
Thank you for letting us know Sandali.

We'll check on it and correct it right away.

**Comment by Rosarangi** [comment]
I fixed the issue. thank you
![IMG-20201211-WA0045](https://user-images.githubusercontent.com/74761716/101924944-4b3a3980-3bf7-11eb-966b-d10e9760dc0a.jpg)
