### ISSUE TITLE
Error on testing 'user information table'

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#6]
When testing **user information** table, unfortunately, it wasn't shown as we excepted. Any user information wasn't disappeared.
Please pay attention to fix this error.
![e1](https://user-images.githubusercontent.com/75560658/103625479-0b017900-4f61-11eb-8c5e-d7315e45c36b.PNG)

**Comment by Rosarangi** [comment]
I'm very sorry about that. It is my fault. I corrected it Sandali. Thank you.
![Screenshot (417)](https://user-images.githubusercontent.com/74761716/103646879-6abb4c80-4f80-11eb-9859-247c90b528f7.png)
