### ISSUE TITLE
Testing error on 'books request' interface of user

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#7]
@Rosarangi  @JSPrasannicca 
When testing **books request** interface, unfortunately, it wasn't shown as we excepted. It wasn't good enough in appearance as shown below.
Please pay attention to make this interface better.    
![e2](https://user-images.githubusercontent.com/75560658/103639365-422d5580-4f74-11eb-923b-3e34cea603f6.PNG)

**Comment by Rosarangi** [comment]
L solved that issue sandali. thank you for point out it
![Screenshot (416)](https://user-images.githubusercontent.com/74761716/103646527-d18c3600-4f7f-11eb-8056-be09f266f59a.png)

**Comment by JSPrasannicca** [comment]
Great works Girls.

Keep up the good work.

Best Regards,
J.S.Prasannicca,
Undergraduate,
Sri Lanka Technological Campus,
Ingiriya Road,
Padukka.
0763667041
