### ISSUE TITLE
Modifying dashboards of user and librarian 

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#8]
@Rosarangi 
To impress more our client, could you please modify the dashboards by adding an image to it instead of keeping it as a blank page.
![s1](https://user-images.githubusercontent.com/75560658/108467516-553d8000-72ab-11eb-9a1d-ebff9cfccb4e.PNG)

**Comment by Rosarangi** [comment]
thank you for point out it. i fixed that issue
![IMG-20210220-WA0051](https://user-images.githubusercontent.com/74761716/108602650-1bfb3200-73c9-11eb-96ef-ef4c2b4c7786.jpg)

**Comment by Rosarangi** [comment]
thank you for point out it. i fixed that issue
![IMG-20210220-WA0050](https://user-images.githubusercontent.com/74761716/108602696-641a5480-73c9-11eb-99a6-d8da53912240.jpg)
