### ISSUE TITLE
Error on modifying dashboards 

### ISSUE THREAD

**Issue by Sandali767** [Library-managment-system/Code#9]
@Rosarangi 
could you please pay attention again for dashboards? You were added an image for dashboards but, now there are no navigation bar. please fix this error. 
![s2](https://user-images.githubusercontent.com/75560658/108468903-6dae9a00-72ad-11eb-84ea-575d1e49af5d.PNG)

**Comment by Rosarangi** [comment]
thank you sandali. I fixed it.
![IMG-20210220-WA0051](https://user-images.githubusercontent.com/74761716/108602617-e6eedf80-73c8-11eb-8154-7641103bb3b4.jpg)
